prueba:
    resource: "@PruebaBundle/Resources/config/routing.yml"
    prefix:   /

rutas_bundle:
    resource: "@AppBundle/Resources/config/rutas.yml" 
    prefix: /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
