pruebas_hola:
    path: /pruebas/hola
    defaults: 
        {_controller: AppBundle:Pruebas:Saluda}
    
pruebas_index:
    path: /pruebas/{nombre}/{apellido}/{raza}
    defaults: 
        {_controller: AppBundle:Pruebas:index,raza:negro,  nombre:Pascual, apellido:Munoz}
    methods: [GET, POST]
    requirements: 
            raza: negro | blanco
            
login: 
    path: /login/{user}
    defaults: 
        {_controller: AppBundle:login:login, user: anonimo }
        
                                           
